### ISSUE TITLE
StringDecoder throws BufferUnderflowException

### ISSUE THREAD

**Issue by bmatheny** [kafka-dev/kafka#38]
I was attempting to use the StringDecoder to pull some JSON strings off a queue. During testing I am sending the same message through 1k times and see the following exception about 80% of the time:

```
java.nio.BufferUnderflowException
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:127)
        at kafka.serializer.StringDecoder.toEvent(Decoder.scala:34)
        at com.tumblr.motherboy.workers.Consumer$$anonfun$act$1$$anonfun$apply$2$$anonfun$apply$3.apply(Main.scala:17)
        at com.tumblr.motherboy.workers.Consumer$$anonfun$act$1$$anonfun$apply$2$$anonfun$apply$3.apply(Main.scala:15)
        at scala.collection.Iterator$class.foreach(Iterator.scala:631)
        at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:29)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:79)
        at kafka.consumer.KafkaMessageStream.foreach(KafkaMessageStream.scala:28)
        at com.tumblr.motherboy.workers.Consumer$$anonfun$act$1$$anonfun$apply$2.apply(Main.scala:15)
        at com.tumblr.motherboy.workers.Consumer$$anonfun$act$1$$anonfun$apply$2.apply(Main.scala:13)
        at scala.actors.ReactorTask.run(ReactorTask.scala:34)
        at scala.actors.ReactorTask.compute(ReactorTask.scala:66)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:147)
        at scala.concurrent.forkjoin.ForkJoinTask.quietlyExec(ForkJoinTask.java:422)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.mainLoop(ForkJoinWorkerThread.java:340)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:325)
```

The remaining 20% of the time, the string deserializes just fine (again, all messages are identical). Discussion on IRC led me to implement my own `StringDecoder` as follows:

```
class StringDecoder extends Decoder[String] {
  def toEvent(message: Message):String = {                                                  
    val buf = message.payload
    val arr = new Array[Byte](buf.remaining)
    buf.get(arr)
    new String(arr)
  }                                       
}  
```

The above code does not throw an exception.

Platform: OS X 10.6.8

Java Version:
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03-384-10M3425)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02-384, mixed mode)

Scala Version: Scala code runner version 2.8.1.final -- Copyright 2002-2010, LAMP/EPFL

Kafka Version: master/trunk

**Comment by kafka-dev** [comment]
Blake, thanks for finding the problem. Do you thing that you can patch the current StringDecoder? I will commit the patch once you have it.

**Comment by bmatheny** [comment]
Sure no problem. Pull request coming shortly.

**Comment by bmatheny** [comment]
In pull request #39, closing this issue ticket.
