### ISSUE TITLE
kafka java client

### ISSUE THREAD

**Issue by ronenhamias** [kafka-dev/kafka#45]
trying to run kafka client from windows client throws exception

i am trying to run kafka client from windows maching both from java 7 and 6
throws exception : 
Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 10000
    at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:876)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
    at kafka.producer.ZKBrokerPartitionInfo.<init>(ZKBrokerPartitionInfo.scala:62)
    at kafka.producer.Producer.<init>(Producer.scala:47)
    at kafka.javaapi.producer.Producer.<init>(Producer.scala:33)
    at kafka.javaapi.producer.Producer.<init>(Producer.scala:40)
    at kafka.examples.Test.main(Test.java:16)

**Comment by junrao** [comment]
We have moved to Apache. Could you post your question there?

Thanks,

Jun
