### ISSUE TITLE
kafka can't produce when using remote zookeeper, connection refused by zookeeper

### ISSUE THREAD

**Issue by xianping** [kafka-dev/kafka#48]
Hi,
I am using kafka 8.0( kafka_2.8.0-0.8.0), zookeeper 3.4.5.  If kafka and zookeeper exist in same machine, it's ok. 
## But if kafka in 192.168.195.178, zookeeper in 192.168.195.177, by using 'bin/kafka-console-producer.sh --broker-list 192.168.195.178:9092 --topic test' in kafka server, it genetates following error messages:

[2014-01-17 17:55:58,468] ERROR fetching topic metadata for topics [Set(test)] from broker [ArrayBuffer(id:0,host:192.168.195.177,port:9092)] failed (kafka.utils.Utils$)
kafka.common.KafkaException: fetching topic metadata for topics [Set(test)] from broker [ArrayBuffer(id:0,host:192.168.195.177,port:9092)] failed
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:67)
        at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
        at kafka.producer.async.DefaultEventHandler$$anonfun$handle$1.apply$mcV$sp(DefaultEventHandler.scala:67)
        at kafka.utils.Utils$.swallow(Utils.scala:187)
        at kafka.utils.Logging$class.swallowError(Logging.scala:105)
        at kafka.utils.Utils$.swallowError(Utils.scala:46)
        at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:67)
        at kafka.producer.async.ProducerSendThread.tryToHandle(ProducerSendThread.scala:104)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:87)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:67)
        at scala.collection.immutable.Stream.foreach(Stream.scala:254)
        at kafka.producer.async.ProducerSendThread.processEvents(ProducerSendThread.scala:66)
        at kafka.producer.async.ProducerSendThread.run(ProducerSendThread.scala:44)
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect(Native Method)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:500)
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
        at kafka.producer.SyncProducer.connect(SyncProducer.scala:146)
        at kafka.producer.SyncProducer.getOrMakeConnection(SyncProducer.scala:161)
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:68)
        at kafka.producer.SyncProducer.send(SyncProducer.scala:112)
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:53)
        ... 12 more
[2014-01-17 17:55:58,471] ERROR Producer connection to 192.168.195.177:9092 unsuccessful (kafka.producer.SyncProducer)
java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect(Native Method)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:500)
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
        at kafka.producer.SyncProducer.connect(SyncProducer.scala:146)
        at kafka.producer.SyncProducer.getOrMakeConnection(SyncProducer.scala:161)
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:68)
        at kafka.producer.SyncProducer.send(SyncProducer.scala:112)
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:53)
        at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
        at kafka.producer.BrokerPartitionInfo.getBrokerPartitionInfo(BrokerPartitionInfo.scala:49)
        at kafka.producer.async.DefaultEventHandler.kafka$producer$async$DefaultEventHandler$$getPartitionListForTopic(DefaultEventHandler.scala:186)
        at kafka.producer.async.DefaultEventHandler$$anonfun$partitionAndCollate$1.apply(DefaultEventHandler.scala:150)
        at kafka.producer.async.DefaultEventHandler$$anonfun$partitionAndCollate$1.apply(DefaultEventHandler.scala:149)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:57)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:43)
        at kafka.producer.async.DefaultEventHandler.partitionAndCollate(DefaultEventHandler.scala:149)
        at kafka.producer.async.DefaultEventHandler.dispatchSerializedData(DefaultEventHandler.scala:95)
        at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:72)
        at kafka.producer.async.ProducerSendThread.tryToHandle(ProducerSendThread.scala:104)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:87)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:67)
        at scala.collection.immutable.Stream.foreach(Stream.scala:254)
        at kafka.producer.async.ProducerSendThread.processEvents(ProducerSendThread.scala:66)
        at kafka.producer.async.ProducerSendThread.run(ProducerSendThread.scala:44)
[2014-01-17 17:55:58,472] WARN Fetching topic metadata with correlation id 1 for topics [Set(test)] from broker [id:0,host:192.168.195.177,port:9092] failed (kafka.client.ClientUtils$)
java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect(Native Method)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:500)
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
        at kafka.producer.SyncProducer.connect(SyncProducer.scala:146)
        at kafka.producer.SyncProducer.getOrMakeConnection(SyncProducer.scala:161)
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:68)
        at kafka.producer.SyncProducer.send(SyncProducer.scala:112)
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:53)
        at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
        at kafka.producer.BrokerPartitionInfo.getBrokerPartitionInfo(BrokerPartitionInfo.scala:49)
        at kafka.producer.async.DefaultEventHandler.kafka$producer$async$DefaultEventHandler$$getPartitionListForTopic(DefaultEventHandler.scala:186)
        at kafka.producer.async.DefaultEventHandler$$anonfun$partitionAndCollate$1.apply(DefaultEventHandler.scala:150)
        at kafka.producer.async.DefaultEventHandler$$anonfun$partitionAndCollate$1.apply(DefaultEventHandler.scala:149)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:57)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:43)
        at kafka.producer.async.DefaultEventHandler.partitionAndCollate(DefaultEventHandler.scala:149)
        at kafka.producer.async.DefaultEventHandler.dispatchSerializedData(DefaultEventHandler.scala:95)
        at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:72)
        at kafka.producer.async.ProducerSendThread.tryToHandle(ProducerSendThread.scala:104)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:87)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:67)
        at scala.collection.immutable.Stream.foreach(Stream.scala:254)
        at kafka.producer.async.ProducerSendThread.processEvents(ProducerSendThread.scala:66)
        at kafka.producer.async.ProducerSendThread.run(ProducerSendThread.scala:44)
[2014-01-17 17:55:58,474] ERROR Failed to collate messages by topic, partition due to: fetching topic metadata for topics [Set(test)] from broker [ArrayBuffer(id:0,host:192.168.195.177,port:9092)] failed (kafka.producer.async.DefaultEventHandler)
[2014-01-17 17:55:58,605] ERROR Producer connection to 192.168.195.177:9092 unsuccessful (kafka.producer.SyncProducer)
java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect(Native Method)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:500)
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
        at kafka.producer.SyncProducer.connect(SyncProducer.scala:146)
        at kafka.producer.SyncProducer.getOrMakeConnection(SyncProducer.scala:161)
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:68)
        at kafka.producer.SyncProducer.send(SyncProducer.scala:112)
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:53)
        at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
        at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:78)
        at kafka.utils.Utils$.swallow(Utils.scala:187)
        at kafka.utils.Logging$class.swallowError(Logging.scala:105)
        at kafka.utils.Utils$.swallowError(Utils.scala:46)
        at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:78)
        at kafka.producer.async.ProducerSendThread.tryToHandle(ProducerSendThread.scala:104)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:87)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:67)
        at scala.collection.immutable.Stream.foreach(Stream.scala:254)
        at kafka.producer.async.ProducerSendThread.processEvents(ProducerSendThread.scala:66)
        at kafka.producer.async.ProducerSendThread.run(ProducerSendThread.scala:44)
[2014-01-17 17:55:58,606] WARN Fetching topic metadata with correlation id 2 for topics [Set(test)] from broker [id:0,host:192.168.195.177,port:9092] failed (kafka.client.ClientUtils$)
java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect(Native Method)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:500)
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
        at kafka.producer.SyncProducer.connect(SyncProducer.scala:146)
        at kafka.producer.SyncProducer.getOrMakeConnection(SyncProducer.scala:161)
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:68)
        at kafka.producer.SyncProducer.send(SyncProducer.scala:112)
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:53)
        at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
        at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:78)
        at kafka.utils.Utils$.swallow(Utils.scala:187)
        at kafka.utils.Logging$class.swallowError(Logging.scala:105)
        at kafka.utils.Utils$.swallowError(Utils.scala:46)
        at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:78)
        at kafka.producer.async.ProducerSendThread.tryToHandle(ProducerSendThread.scala:104)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:87)
        at kafka.producer.async.ProducerSendThread$$anonfun$processEvents$3.apply(ProducerSendThread.scala:67)
        at scala.collection.immutable.Stream.foreach(Stream.scala:254)
        at kafka.producer.async.ProducerSendThread.processEvents(ProducerSendThread.scala:66)
        at kafka.producer.async.ProducerSendThread.run(ProducerSendThread.scala:44)

**Comment by junrao** [comment]
Could you subscribe to our Apache mailing list?
http://kafka.apache.org/contact.html

Thanks,

Jun

**Comment by xianping** [comment]
i tested again by configuring kafka host and zookeeper host with hostname string instead of ip address, the new test process below:
1,first try to produce topici 'ximi' in server3 (kafka server)
[root@server3 kafka_2.8.0-0.8.0]# bin/kafka-console-producer.sh --broker-list server3:9092 --topic ximi  
ximi gest
[2014-01-18 10:57:04,250] WARN Error while fetching metadata [{TopicMetadata for topic ximi -> 
No partition metadata for topic ximi due to kafka.common.LeaderNotAvailableException}] for topic [ximi]: class kafka.common.LeaderNotAvailableException  (kafka.producer.BrokerPartitionInfo)
[2014-01-18 10:57:04,272] WARN Error while fetching metadata [{TopicMetadata for topic ximi -> 
No partition metadata for topic ximi due to kafka.common.LeaderNotAvailableException}] for topic [ximi]: class kafka.common.LeaderNotAvailableException  (kafka.producer.BrokerPartitionInfo)
[2014-01-18 10:57:04,273] ERROR Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: ximi (kafka.producer.async.DefaultEventHandler)
test new me
hello
2, Second try to consume...
[root@server3 kafka_2.8.0-0.8.0]# bin/kafka-console-consumer.sh --zookeeper server3:3181 --topic ximi --from-beginning  
[2014-01-18 10:57:59,971] WARN [console-consumer-65386_server3-1390013879485-3f815f14], no brokers found when trying to rebalance. (kafka.consumer.ZookeeperConsumerConnector)
3, Third, surprisingly I can find the topic in kafka topic list.
[root@server3 kafka_2.8.0-0.8.0]# bin/kafka-list-topic.sh --zookeeper server2:3181  
topic: test     partition: 0    leader: 2       replicas: 2     isr: 2
topic: ximi     partition: 0    leader: 2       replicas: 2     isr: 2
topic: xp       partition: 0    leader: 2       replicas: 2     isr: 2

**Comment by xianping** [comment]
hi ,
Who can help me ?

# 

Guys,
it can work if i use kafka server (0.8) and zookeeper (3.4.5) in same machine (centos 6.3 final), but failed by seperating them into two machines.
1, when trying to produce, find some error messages,
2,, try to consume, failed because " WARN [console-consumer-65386_server3-1390013879485-3f815f14], no brokers found when trying to rebalance. (kafka.consumer.ZookeeperConsumerConnector)"
But the topic is created successfully in kafka datadir.
I have logged details in github issue 48 (https://github.com/kafka-dev/kafka/issues/48)

please help me

Thanks

At 2014-01-18 00:18:31,"Jun Rao" notifications@github.com wrote:
Could you subscribe to our Apache mailing list?
http://kafka.apache.org/contact.html

Thanks,

Jun

**Comment by junrao** [comment]
We are no longer on github and have moved to Apache. Could you post you
question to Apache mailing list? There is a bigger community there.

Thanks,

Jun

**Comment by xianping** [comment]
I have subscribed and sent to users@kafka.apache.org, but there is no reply. Should i send to dev@kafka.apache.org?

**Comment by jric** [comment]
You might double-check that Kafka is running on the port you think it is.  I was having similar problems, and it turned out I was trying to produce to the Zookeeper port on accident.

**Comment by maxivak** [comment]
Try port 6667 instead of 9092.
The default port Ambari uses for Kafka brokers = 6667.

So it must be 

```
`bin/kafka-console-producer.sh --broker-list 192.168.195.178:6667 --topic test`
```
